### ISSUE TITLE
Error "Failed to get embedding for chunk of page..."

### ISSUE THREAD

**Issue by lmalevich** [cosmocode/dokuwiki-plugin-aichat#1]
Hello, can you suggest why this error can occur when entering a command ` php bin/plugin.php aichat embed` in cli? 

`Failed to get embedding for chunk of page wiki:syntax: OpenAI API returned error: Rate limit reached for default-text-embedding-ada-002 in organization org-2NmIpMDQPLLDd8udkShoTG2U on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.`

A bit of input: my wiki has about 2000 pages, OpenAI API not paid for, using php version 8.1, dokuwiki version "Jack Jackrum"

**Comment by splitbrain** [comment]
You will need to add a payment method to use this plugin.

**Comment by lmalevich** [comment]
At first, it gave me errors:
`Failed to get embedding for chunk of page wiki:syntax: OpenAI API returned error: Rate limit reached for default-text-embedding-ada-002 in organization org-2NmIpMDQPLLDd8udkShoTG2U on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.`

But ended up processing 4 pages and hovered that way:
`✓ wiki:dokuwiki split into 1 chunks`
`✓ wiki:syntax split into 10 chunks`
`✓ start split into 2 chunks`
`✓ wiki:welcome split into 1 chunks`


After I stop running the command via ctrl+z and run the command again, it gives this and hangs in this state:
`ℹ Reusing chunks for wiki:dokuwiki`
`ℹ Reusing chunks for wiki:syntax`
`ℹ Reusing chunks for start`
`ℹ Reusing chunks for wiki:welcome`
