### ISSUE TITLE
Data on tables

### ISSUE THREAD

**Issue by manuel-dev** [cosmocode/dokuwiki-plugin-aichat#15]
### Feature Description

Hello, I find this plugin fascinating. Could there be an option to also consider the information contained in table rows when providing an answer? For example, in a table with these data:
^ Fruit ^ KCal ^ GI ^
| Cherry | 64 | low |
| Apple | 60 | low |
| Watermelon | 70 | high |
| Kiwi | 58 | medium |

If I ask which fruits have low GI, it doesn't give an answer. I know it's logical that it doesn't find it, but could there be a workaround instead of having to write full sentences for each item?
Thanks and keep the good work.

**Comment by splitbrain** [comment]
One question. Do you have the [text plugin](https://www.dokuwiki.org/plugin:text) installed?
