### ISSUE TITLE
Add support for Ollama embedding model :  nomic-embed-text

### ISSUE THREAD

**Issue by magicmars35** [cosmocode/dokuwiki-plugin-aichat#16]
### Feature Description

Hi. Is is possible tu use nomix-embed-text as embedding model ?

https://ollama.com/library/nomic-embed-text

I try to run embbeding with "Ollama text-embedding-ada-002". 
how tu run it ? (I have Ollama installed, and working fine)

When I try to load it : 

$ php bin/plugin.php aichat embed

✓ Skipping pages matching /:(playground|sandbox)(:|$)/
☠ Failed to initialize EmbeddingModel for Ollama: Ollama base URL not configured

thank you

**Comment by splitbrain** [comment]
The ollama classes are not in a working state currently. They were an experiment only. Contact us if you want us to support local models through ollama.
