### ISSUE TITLE
Restrict access to namespaces

### ISSUE THREAD

**Issue by Ederhex** [cosmocode/dokuwiki-plugin-aichat#5]
Hello,

First of al thanks for the plugin. We decided to test the plugin for our community project documentation. We use namespaces for different release documentation. The chatbot now gives the same same answer multiple times. Since it's not aware about the versioning structure it doesn't give any context why you get the same answer multiple times.

Dokuwiki might not be the best solution for documentation versioning but it would really help if there was a way to restrict this plugin to use only selected namespaces. 

Anyway thanks for your plugins I would like to hear weather you think my request is reasonable.

**Comment by macin** [comment]
I have similar problem. Looking forward for a simple filter based on workspaces allowed
