### ISSUE TITLE
Temperature adjustment?

### ISSUE THREAD

**Issue by Hegghammer** [cosmocode/dokuwiki-plugin-aichat#7]
Thanks a lot for building this -- it's a really important contribution. 

Maybe I missed it, but I can't seem to find a way to adjust the temperature for the model's answers. I would personally like to have it at 0, but my experimentation so far suggests it's set to a value higher than this.

**Comment by splitbrain** [comment]
The temperature is current hard-coded but already at zero:

https://github.com/cosmocode/dokuwiki-plugin-aichat/blob/db36318f90b450016d7d88f895a7f448690d437b/Model/OpenAI/GPT35Turbo.php#L123
